name: Build and Run Project

on: push

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        npm install
        npm install -g node-gyp
        
    - name: Compile JS Addon
      run: node-gyp configure build

    - name: Build Server
      run: |
        node server.js &
        sleep 10 &&
        curl http://localhost:3001/start > output.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: server-output
        path: output.txt

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: server-output
        path: skyRunner/output.txt
    - name: Display structure of downloaded files
      run: ls -R

    - name: Commit recompiled binaries
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add skyRunner
        git commit -m "Upload Build Artifacts"
    - name: Push recompiled binaries
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
